spring:
  application:
    name: ticketflow
  profile:
    default: dev
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: validate
      properties:
        hibernate:
          format_sql: true
    flyway:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics