spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:ticketflow}
    username: ${DB_USER:ticketflow}
    password: ${DB_PASSWORD:ticketflow}
  jpa:
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
