CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT NOT NULL REFERENCES users (id),
    action VARCHAR(64) NOT NULL,
    entity_type VARCHAR(64) NOT NULL,
    entity_id BIGINT NOT NULL,
    payload_json JSONB,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_audit_entity ON audit_logs (entity_type, entity_id);