create table users (
    id bigint generated by default as identity primary key,
    email varchar(255) not null unique,
    password_hash varchar(255) not null,
    full_name varchar(255) not null,
    enabled boolean not null default true,
    created_at TIMESTAMPTZ not null,
    updated_at TIMESTAMPTZ not null
);

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role VARCHAR(32) NOT NULL,
    PRIMARY KEY (user_id, role)
);

CREATE INDEX idx_users_email ON users (email);