CREATE TABLE venues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    capacity INTEGER NOT NULL,
    organizer_id BIGINT NOT NULL REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id BIGINT NOT NULL REFERENCES users (id),
    venue_id BIGINT NOT NULL REFERENCES venues (id),
    title VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(255) NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    sales_starts_at TIMESTAMPTZ NOT NULL,
    sales_ends_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(23) NOT NULL,
    banner_url VARCHAR(512),
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE ticket_tiers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events (id),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    price_currency VARCHAR(3) NOT NULL,
    total_quantity INTEGER NOT NULL,
    reserved_quantity INTEGER NOT NULL DEFAULT 0,
    sold_quantity INTEGER NOT NULL DEFAULT 0,
    max_per_order INTEGER NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_tier_quantity CHECK ( reserved_quantity + sold_quantity <= total_quantity ),
    CONSTRAINT chk_tier_nonneg CHECK ( reserved_quantity >= 0 AND sold_quantity >= 0 )
);

CREATE INDEX idx_venues_organizer_id ON venues (organizer_id);
CREATE INDEX idx_events_organizer_id ON events (organizer_id);
CREATE INDEX idx_events_venue_id ON events (venue_id);
CREATE INDEX idx_ticket_tiers_event_id ON ticket_tiers (event_id);

CREATE INDEX idx_events_status_starts_at ON events (status, starts_at);

