CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    event_id BIGINT NOT NULL REFERENCES events (id),
    status VARCHAR(32) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE reservation_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT NOT NULL REFERENCES reservations (id) ON DELETE CASCADE,
    tier_id BIGINT NOT NULL references ticket_tiers (id),
    quantity INTEGER NOT NULL,
    unit_price_amount NUMERIC(2, 10) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_reservation_user_id ON reservations (user_id);
CREATE INDEX idx_reservations_event_id ON reservations (event_id);
CREATE INDEX idx_reservation_items_reservation_id ON reservation_items (reservation_id);
CREATE INDEX idx_reservation_items_tier_id ON reservation_items (tier_id);

CREATE INDEX idx_reservations_status_expires ON reservations (status, expires_at);