CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders (id),
    tier_id BIGINT NOT NULL REFERENCES ticket_tiers (id),
    event_id BIGINT NOT NULL REFERENCES events (id),
    owner_user_id BIGINT NOT NULL REFERENCES users (id),
    uuid_code VARCHAR(32) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_tickets_id ON tickets (id);
CREATE INDEX idx_tickets_tier_id ON tickets (tier_id);
CREATE INDEX idx_tickets_owner_user_id ON tickets (owner_user_id);